# Site settings
title: STFFE - Stinky Tofu Front-End Blog
motto: 「Stinky Tofu Front-End ~ 前端是工作，臭豆腐是生活，对于我们，缺一不可。我们在星城，倾听世界 。」
email: your-email@domain.com
description: > # 「Stinky Tofu Front-End ~ 前端是工作，臭豆腐是生活，对于我们，缺一不可。我们在星城，倾听世界 。」
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stffe.github.com" # the base hostname & protocol for your site
twitter_username: stffe
github_username:  stffe

# Build settings
markdown: kramdown

# Syntax highlighting
highlightstyle: 'arta'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

highlighter: 'rouge'

kramdown:
  syntax_highlighter: rouge
